In [31]:
import numpy as np

dataset = np.array([[10, 6],[11, 4], [8, 5], [3, 3], [2, 2.8], [1, 1]])
dataset = np.array([[-4, -6],[3, 5]])
dataset.shape

(2, 2)

In [32]:
Cx = np.cov(dataset.T)
w,v = np.linalg.eig(Cx)
Cx, w, v

(array([[24.5, 38.5],
        [38.5, 60.5]]),
 array([ 0., 85.]),
 array([[-0.84366149, -0.53687549],
        [ 0.53687549, -0.84366149]]))

In [33]:
Cx2 = 1/(dataset.shape[0]-1) * dataset.T @ dataset
Cx2

array([[25., 39.],
       [39., 61.]])

In [34]:
#say we want to keep 1 dimensions of the 2 we originally had
w_ord_indx = np.argsort(np.abs(w))[::-1]
feature_vector = v[:,w_ord_indx[:1]]
feature_vector

array([[-0.53687549],
       [-0.84366149]])

In [2]:
test1d = [10, 20, 30]
sum(test1d)

60

In [6]:
test2d = [[10], [20], [30]]
import numpy as np
np.sum(test2d, axis=0), np.sum(test2d, axis=1)

(array([60]), array([10, 20, 30]))